### ISSUE TITLE
Warning: Please enable the plugins

### ISSUE THREAD

**Issue by nicksavov** [OSTraining/OSMeta#17]
administrator/index.php?option=com_osmeta generates the following messages even though the plugins are indeed enabled:

Warning
Please enable the content plugin: osmetacontent.

Please enable the system plugin: osmetarenderer.

**Comment by andergmartins** [comment]
@nicksavov I can't reproduce this with the current version, can you try again, please? Thanks

**Comment by nicksavov** [comment]
I doubt it's still applicable. Let's close :)
