### ISSUE TITLE
Textarea allow to add more text over the limit

### ISSUE THREAD

**Issue by htmgarcia** [OSTraining/OSMeta#32]
Moe than 70 for title, more than 160 for description
![textlong](https://cloud.githubusercontent.com/assets/4999794/5031945/d4ca7fca-6b1f-11e4-8865-7656bb1008b3.jpg)

**Comment by andergmartins** [comment]
I think it is not a bug, since that char count is "only" a good practice, but I agree that we need to do anything to incentivate our users to follow that. Maybe a good "fix"  would to implement this request: #7

**Comment by nicksavov** [comment]
Agreed

**Comment by andergmartins** [comment]
This issue was improved on the 1.2.0 release, so I'm closing it. Feel free to open it again if needed.
