### ISSUE TITLE
Pro feature: track search results

### ISSUE THREAD

**Issue by htmgarcia** [OSTraining/OSMeta#35]
Assign meta tags to every single search results page

**Comment by andergmartins** [comment]
@htmgarcia I didn't get your point :) , can you please give me an example, perhaps?
Tks

**Comment by stevejburge** [comment]
Doesn't com_search have an option to record searches already?

**Comment by htmgarcia** [comment]
I'm not aware of that. 
My suggestion is focused in mainly provided SEO in search results.

I'm closing this issue for now. If somebody later consider worth giving a try, feel free to reopen.
