### ISSUE TITLE
Generate Description => 255 characters

### ISSUE THREAD

**Issue by nicksavov** [OSTraining/OSMeta#42]
Not sure if this is a bug or not, but the Generate Description button brings in ~255 characters of text, but the info says "This should be no longer than 160 characters" for that field.

Is it by design that there's extra text so that the admin can trim out what's not needed?

**Comment by andergmartins** [comment]
I would say, let's change that to be no longer than 160 by default. We can add a param allowing to customize the chars limit for that action.

**Comment by stevejburge** [comment]
Good catch @nicksavov and @andergmartins. 160 is best.
