### ISSUE TITLE
Move the homepage fields to an specific content type

### ISSUE THREAD

**Issue by andergmartins** [OSTraining/OSMeta#44]
Right now, the homepage fields appears for any content type, what seems a little bit inconsistent.
So we will have as Content Type: Homepage, Article, Category, etc...

**Comment by andergmartins** [comment]
![osmeta - administration - osmeta meta tags manager 2015-01-07 18-42-10](https://cloud.githubusercontent.com/assets/407131/5652989/41bef9d2-969d-11e4-9883-590d54ed5e9f.png)

**Comment by stevejburge** [comment]
Good point. Maybe make the homepage available only via the dropdown?

**Comment by andergmartins** [comment]
:+1:

**Comment by htmgarcia** [comment]
I like it :+1:
