### ISSUE TITLE
Convert the Content Type dropdown filter to a submenu

### ISSUE THREAD

**Issue by andergmartins** [OSTraining/OSMeta#45]
It seems more Joomla friendly...
![osmeta - administration - article manager articles 2015-01-07 18-49-42](https://cloud.githubusercontent.com/assets/407131/5653076/1c59f72c-969e-11e4-8a6d-c8de2d5bc8b5.png)
![osmeta25 - administration - article manager articles 2015-01-07 18-50-17](https://cloud.githubusercontent.com/assets/407131/5653075/1c591dde-969e-11e4-918c-5c23b37c41b7.png)

**Comment by stevejburge** [comment]
Good point. Yes, let's use the Joomla defaults

**Comment by andergmartins** [comment]
Cool, adding to the milestone
