### ISSUE TITLE
Best way to handle the existing page titles

### ISSUE THREAD

**Issue by stevejburge** [OSTraining/OSMeta#54]
Lots of people have been using these until now and they conflict with OSMeta

Should we offer an option to import and delete?

![ostraining_-_administration_-_menu_manager__edit_menu_item](https://cloud.githubusercontent.com/assets/3868028/5704067/d3f576e0-9a3b-11e4-9e9c-11f7682925a9.png)

**Comment by andergmartins** [comment]
I don't think it is being a conflict right now. For menu items, OSMeta is actually using that field to load and store the title. So if the user have a lot of existent menus and custom page titles (in that field), OSMeta will load it by default. And after save, it will change that data on its source. I'm avoiding to duplicate the data in the db. OSMeta still has a legacy custom db table, but I'm progressively removing it and saving all the metadata in the original source.

**Comment by stevejburge** [comment]
Sorry, I think I deleted the evidence from OSTraining, but the page title was winning.

Also, when we first launched, importing the page titles was a feature request. Perhaps we ignore the conflict and offer an import and delete option?

**Comment by andergmartins** [comment]
Right, maybe I'm misunderstanding anything here. What I have tested was a fresh Joomla install with an article and menu poiting to it. Changed the browser title inside the menu form and after installed OSMeta. The custom title appeared on the menu item in OSMeta and saved without problems. 

Regarding the OSTraining evidence, I have a local copy here that I made probably before you delete/update the item. Do you remember the title at least? I can try to reproduce locally them. 

Sorry, it is still not so clear for me :)

**Comment by stevejburge** [comment]
Yes, the blog pages with OSTraining were taking the titles from the "Blog Categories" menu

For import, maybe that's just the best solution. A lot of people will already have data in there.

**Comment by andergmartins** [comment]
Humm, right, I think I got it now. That is probably because the priority is Menu -> Article/Item... if the blog post is using the item id from "Blog Categories", yes, it will grab the data from the menu for all posts, instead of from the item.

**Comment by stevejburge** [comment]
Yes, that's it. If an import is possible, that would solve it.

**Comment by andergmartins** [comment]
If I got it well, probably inverting the priority would fix: Article/Item > Menu... so if the article data is not empty (title/descr) it will use the specific one. Otherwise, it will look for the menu metadata and display it

**Comment by stevejburge** [comment]
Thanks. That solves it.

Maybe for later, import could be an added feature, to help new users.

**Comment by andergmartins** [comment]
Cool, thanks, that is faster.

The "import" idea is still not clear for me. Hearing "import" sounds like they want to copy the metadata from somewhere into each menu. The problem I see is that the menu item is neutral source, in terms of extensions. It is able to set the metadata for items coming from any extension and we can't support an import option for all available components. We can allow to import, but from specific sources...

**Comment by stevejburge** [comment]
Ok, no worries. Let's leave this and come back if someone asks again.

**Comment by andergmartins** [comment]
Ok :+1:

**Comment by andergmartins** [comment]
Fixing the priority for menu metadata on the issue https://github.com/OSTraining/OSMeta-Pro/issues/16
