### ISSUE TITLE
Small pagination bug

### ISSUE THREAD

**Issue by stevejburge** [OSTraining/OSMeta#55]
The pagination is definitely buggy. 

1) It's not consistent on how many items are showing. You can see OSTraining as an example - switch from 100 to 50 and the pagination is inconsistent.

2) if you are inside the pagination and click "Copy item title to search engine title" you will go straight to the first page of pagination. It's confusing - you need to click back through to find the titles you were editing.

3) Should we move the pagination to the filters at the top?

**Comment by andergmartins** [comment]
In regard to 3) probably it will be fixed in #31
