### ISSUE TITLE
Doesn't handle external links very well

### ISSUE THREAD

**Issue by stevejburge** [OSTraining/OSMeta#58]
Here's a menu link that is an external link. The URL arrow is broken and the title is blank.

If a menu link is an external link, should we disable metadata?
![ostraining_-_administration_-_osmeta_meta_tags_manager](https://cloud.githubusercontent.com/assets/3868028/5704864/1089e3e6-9a43-11e4-88ab-2c847fcb0b76.png)

**Comment by andergmartins** [comment]
Yeah, good point. I don't think we need metadata for external links. In case the external link is pointing to an internal page, that page should have a menu item too, so the custom metadata still can be set. So I vote +1, let's disable metadata for external links.

**Comment by andergmartins** [comment]
Moved to the Pro repo
