### ISSUE TITLE
Link to view article

### ISSUE THREAD

**Issue by stevejburge** [OSTraining/OSMeta#6]
Let's add a small icon that links to the front of the site.

This will allow people to view the article on their site

![view](https://f.cloud.github.com/assets/3868028/2222359/90feaaaa-9a64-11e3-99b8-f7c743b92382.png)

**Comment by andergmartins** [comment]
![osmeta - administration - osmeta meta tags manager 2015-01-07 17-54-06](https://cloud.githubusercontent.com/assets/407131/5652346/b6d28d62-9696-11e4-99ba-e886e91c0db7.png)
![osmeta25 - administration - osmeta meta tags manager 2015-01-07 17-53-47](https://cloud.githubusercontent.com/assets/407131/5652347/b6d375a6-9696-11e4-8c21-41b0af2878c2.png)
