### ISSUE TITLE
Character counter

### ISSUE THREAD

**Issue by stevejburge** [OSTraining/OSMeta#7]
Can we show people how many characters they've entered?

Maybe a red warning if they go over 70 characters (title) or 160 characters (description)

![counter](https://f.cloud.github.com/assets/3868028/2222505/84b330a2-9a66-11e3-967a-1b168954db67.png)

**Comment by andergmartins** [comment]
Implementation idea taken from WordPress
![screen shot 2015-01-02 at 9 58 08 am](https://cloud.githubusercontent.com/assets/407131/5597034/957ecaee-9282-11e4-9549-0d3bc7cc1583.png)

**Comment by andergmartins** [comment]
![osmeta - administration - osmeta meta tags manager 2015-01-07 15-39-01](https://cloud.githubusercontent.com/assets/407131/5650191/5b692688-9683-11e4-924d-506cfb5fd0c6.png)

**Comment by stevejburge** [comment]
Nice work @andergmartins !

**Comment by nicksavov** [comment]
+1 :)

**Comment by andergmartins** [comment]
Tks :)
