### ISSUE TITLE
Meta Keywords

### ISSUE THREAD

**Issue by nicksavov** [OSTraining/OSMeta#77]
See:
https://secure.helpscout.net/conversation/83455428/12171/

**Comment by stevejburge** [comment]
I hear him, but we did the right thing to take them out

**Comment by nicksavov** [comment]
Agreed

**Comment by nicksavov** [comment]
One more:
https://secure.helpscout.net/conversation/85314047/12275/

He gives the following video for support:
https://www.youtube.com/watch?feature=player_detailpage&v=m-wo8BGQbKU#t=365

**Comment by nicksavov** [comment]
Based on Google's words (e.g. https://www.youtube.com/watch?v=jK7IPbnmvVU) and the other major search engines, they don't appear to use it, except for a spam signal

**Comment by nicksavov** [comment]
Two more at https://www.alledia.com/forum/osmeta/222-feature-request-bulk-editing-meta-keywords/#1412

I'm going to go ahead and close this item. Let's reopen it if we get any more requests and see what percentage of users would like it.
