### ISSUE TITLE
Can't access the component

### ISSUE THREAD

**Issue by htmgarcia** [OSTraining/OSMeta#83]
@andergmartins there is a bug in OSMeta after the update of Joomla 3.4.4 - reported by 2 users

Confirmed in: https://www.alledia.com/forum/oscontent/241-cant-access-the-component/

**Comment by nicksavov** [comment]
Looks like that's for OSContent, rather than OSMeta. Closing in favor of https://github.com/OSTraining/OSContent/issues/57

**Comment by htmgarcia** [comment]
lol - sorry about that

**Comment by nicksavov** [comment]
:D No problem at all!
